pipeline {
    agent any

    tools{
        go '1.21'
    }

    stages {
        stage('Build') {
            environment {
                        // Set the target OS and architecture
                        GOOS   = 'linux'
                        GOARCH = 'amd64'
            }
            steps {
                sh 'go build -o blogserver'
            }
        }
        stage('Deploy') {
            steps{
                sshPublisher(
                    publishers: [sshPublisherDesc(configName: 'ec2-54-234-185-179',
                    transfers: [sshTransfer(cleanRemote: false,
                    excludes: '',
                    execCommand: 'pgrep -f blogserver | xargs kil',
                    execTimeout: 120000,
                    flatten: false,
                    makeEmptyDirs: false,
                    noDefaultExcludes: false,
                    patternSeparator: '[, ]+',
                    remoteDirectory: '',
                    remoteDirectorySDF: false,
                    removePrefix: '',
                    sourceFiles: '')],
                    usePromotionTimestamp: false,
                    useWorkspaceInPromotion: false,
                    verbose: false)]
                )
                sshPublisher(
                    publishers:[sshPublisherDesc(configName: 'ec2-54-234-185-179',
                    transfers:
                    [sshTransfer(cleanRemote: false,
                    excludes: '',
                    execCommand: '~/jenkins_build/blogserver',
                    execTimeout: 120000,
                    flatten: false,
                    makeEmptyDirs: false,
                    noDefaultExcludes: false,
                    patternSeparator: '[, ]+',
                    remoteDirectory: 'jenkins_build',
                    remoteDirectorySDF: false,
                    removePrefix: '',
                    sourceFiles: '**/blogserver')],
                    usePromotionTimestamp: false,
                    useWorkspaceInPromotion: false,
                    verbose: false)]
                )
            }
        }
    }
}