pipeline {
    agent any

    tools{
        go '1.21'
    }

    stages {
       node {
        stage('Build') {
            steps {

                    sh 'ls -l'
                    dir ('build') {
                        sh 'go build -o blogserver .'
                    }
                    sh 'ls -l'
                }
                sh 'readlink -f blogserver'
            }
        }
        stage('Deploy') {
            steps{
                sshPublisher(publishers: [sshPublisherDesc(configName: 'ec2-54-234-185-179', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '~', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'Github Pipline/build/*')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}